version: "3"

services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env   # <-- load secrets from local .env, not in docker-compose
    restart: always

  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}       # fallback if not in env
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"

volumes:
  pgdata: