name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Test Key Format
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | wc -l

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.13
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/e-ticketing
            git pull origin main
            sudo docker-compose down
            sudo docker-compose up -d --build
